version: "3"
services:
  backend:
    build: ./Server/scrooge
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/scrooge
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafy

  frontend:
    build: ./scrooge-react
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://host.docker.internal:8081

volumes:
  mysql-data:
